/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import asteroidAtari.GameGui;
import javafx.application.Application;

public class App {
	public static void main(String[] args) {
        Application.launch(GameGui.class);
    }
}
